### ISSUE TITLE
Implement Webhook listener to start ETL

### ISSUE THREAD

**Issue by dr0i** [hbz/rpb#18]
See https://github.com/hbz/lobid-resources/issues/1469 - on which this issue here depends.

**Comment by dr0i** [comment]
Atm the data's reindexing is scheduled via cron at `Mondays 6:00`. This is suboptimal for it could be closer at the finishing of ETL of the lobid-resources index', using a Webhook.

**Comment by acka47** [comment]
This might also be superfluous now with having a separate index for RPB independent from lobid, see https://github.com/hbz/rpb/issues/21#issuecomment-1774636736

**Comment by dr0i** [comment]
Right. Closing.
