### ISSUE TITLE
RPB introduces doublettes

### ISSUE THREAD

**Issue by dr0i** [hbz/rpb#21]
See e.g. http://test.lobid.org/resources/search?q=hbzId:CT001004829&format=json .

**Comment by acka47** [comment]
Das wird jetzt erstmal gelöst, indem wir einen eigenen Index für die RPB benutzen, anstatt die Daten nach lobid zu spielen. Gründe für diesen Umschwung sind:

1. Vor allem gibt es viele zusätzliche Sacherschließungsinformationen in der RPB, die noch nicht in lobid sind. Um die reinzubekommen, müssten wir also ein paar Alma-Bulk-Updates einspielen.
2. Davor müssten wir aber erst einmal sicherstellen, dass der größte Teil der in lobid vorhandenen RPB-Titel auch auf den jeweiligen lobid-Titel gematcht ist. Dafür haben wir u.a. das Ticket RPB-51 "Monographien mit lobid-resources reconcilen", das wir bisher nicht bearbeitet haben.

Diese Fragen wollen wir dann im Kontext einer möglichst kompletten Migration der RPB von Strapi nach Alma angehen. Dieses Ticket können wir dann m.E. schließen, oder @dr0i ?

**Comment by dr0i** [comment]
Ack. Closing.
