### ISSUE TITLE
Some result list links lead to not-found pages

### ISSUE THREAD

**Issue by fsteeg** [hbz/rpb#29]
Probably related to the change of rpbId (with/without `RPB` prefix). See http://rpb.lobid.org/search?t=MultiVolumeBook (links have no `RPB` prefix). But others do: http://rpb.lobid.org/search.

Edit: Resources without prefix: http://rpb.lobid.org/search?q=_exists_:almaMmsId

I suspect the entries we transform from the Allegro data have `RPB`, while those coming in via Alma don't. We should unify that, but to what? Plain IDs like for the almaMmsId? This is also how the old rpb-URLs work (e.g. `http://www.rpb-rlp.de/929t920633`). In lobid-resources, for the zdbId, we can currently access both with plain ID and with `ZDB-` prefix (and IIRC we use the latter format in some links).

I think we should unify to e.g. `http://rpb.lobid.org/929t920633` (currently [here](http://rpb.lobid.org/RPB929t920633)).

**Comment by acka47** [comment]
> I think we should unify to e.g. `http://rpb.lobid.org/929t920633`

+1 We should probably then also update the IDs in the JSON which currently carry the `RPB` prefix, e.g.:
`"rpbId": "RPB929t920633"`

**Comment by fsteeg** [comment]
As a first step, I've only made the non-prefixed links resolvable, and did not change the transformation. This way, we can compare the Alma and the Allegro entries:

So all RPB entries coming from Alma:
http://test.rpb.lobid.org/search?q=_exists_:almaMmsId

Now do resolve, e.g. the third:
http://test.rpb.lobid.org/121t080049

And we can compare them to the entry coming in via Allegro data by adding the `RPB` prefix, e.g.:
http://test.rpb.lobid.org/RPB121t080049

Now if we'd change the transformation to drop the prefix we'd basically replace the Alma entry with the Allegro entry. I'm not sure what our plan here was, both versions seem to bring in information the other lacks (e.g. items from Alma, classification from Allegro).

**Comment by acka47** [comment]
Sounds like a good solution for now to be able to compare Allegro- and Alma-based entries.

> Now if we'd change the transformation to drop the prefix we'd basically replace the Alma entry with the Allegro entry. I'm not sure what our plan here was, both versions seem to bring in information the other lacks (e.g. items from Alma, classification from Allegro).

We want to use the Alma-based records where possible. We will need to bulk update the lacking RPB classification data in Alma at some point.
