### ISSUE TITLE
Fehlerhafte Integrationtest und alte lobid-Abfragen mit @graph

### ISSUE THREAD

**Issue by TobiasNx** [hbz/rpb#38]
Zugehöriges Jira-Ticket: [RPB-107](https://jira.hbz-nrw.de/browse/RPB-107)

Diese erzeugen Errormeldungen in den Logs von Lobid-Resources:

https://github.com/hbz/rpb/blob/914e3b28e8f4f626513e9e2757b18ca5cb4c563b/test/tests/ExternalIntegrationTest.java#L83-L103
https://github.com/hbz/rpb/blob/914e3b28e8f4f626513e9e2757b18ca5cb4c563b/app/controllers/nwbib/Classification.java#L233
https://github.com/hbz/rpb/blob/914e3b28e8f4f626513e9e2757b18ca5cb4c563b/app/views/tags/result_short.scala.html#L21-L22
https://github.com/hbz/rpb/blob/914e3b28e8f4f626513e9e2757b18ca5cb4c563b/app/views/TableRow.java#L184-L185

Auch gibt es multiVolumeWork nicht mehr in lobid.

**Comment by TobiasNx** [comment]
Nein, bisher ist nur ein Datei angepasst worden: https://github.com/hbz/rpb/blob/914e3b28e8f4f626513e9e2757b18ca5cb4c563b/test/tests/ExternalIntegrationTest.java#L83-L103

Die anderen müssen auch noch geändert werden, sowohl in nwbib, als auch rpb

**Comment by TobiasNx** [comment]
Das kann ich aber nicht: https://github.com/search?q=repo%3Ahbz%2Frpb+%40graph&type=code

**Comment by dr0i** [comment]
Dieses Issue besteht eigentlich aus zwei Issues. Das `@graph` ist gelöst mit #57. Die Testproblematik besteht weiterhin, und es wäre auch zu diskutieren _ob_ die angepasst oder `@Ignored` oder gelöscht werden sollten ... Momentan macht githubactions lediglich `sbt "test-only tests.CITests"` - und wir sollten uns ebenso darauf beschränken resp. die Anzahl der momentan ausgegebenen Fehler als Erwartungswert nehmen wenn wir etwas neues implementieren oder ändern.
Dieses Ticket wird geschlossen.
